/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MFmgr (void);
  
GtkWidget *MFmgr;
  
GtkWidget *radiobtn_Fan_Silent;
GtkWidget *radiobtn_Fan_Normal;
GtkWidget *radiobtn_Fan_Cool;
  
GtkWidget *radiobtn_LED_On;
GtkWidget *radiobtn_Auto;
GtkWidget *radiobtn_Off;
  
GtkWidget *radiobtn_touchPad_enable;
GtkWidget *radiobtn_touchPad_disable;
GtkWidget *radiobtn_touchPad_only;
