/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "talkport.h"

int
main (int argc, char *argv[])
{
  if(argc == 1) {
	  GtkWidget *MFmgr;

#ifdef ENABLE_NLS
	  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
	  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	  textdomain (GETTEXT_PACKAGE);
#endif

	  gtk_set_locale ();
	  gtk_init (&argc, &argv);

	  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

	  /*
	   * The following code was added by Glade to create one of each component
	   * (except popup menus), just so that you see something after building
	   * the project. Delete any components that you don't want shown initially.
	   */
	  MFmgr = create_MFmgr ();
	  gtk_widget_show (MFmgr);

	  gtk_main ();
  } else if(argc == 4) {
	  writeFanSpeed(atoi(argv[1]));
	  writeKeypad(atoi(argv[2]));
	  switch(atoi(argv[3])) {
		  case 0:
			  system("synclient TouchpadOff=1");
			  break;
		  case 1:
			  system("synclient TouchpadOff=2");
			  break;
		  case 2:
			  system("synclient TouchpadOff=0");
			  break;
		  default: ;
	  }
  } else ;

	  return 0;
}

